apiVersion: v1
kind: Pod
metadata:
  name: pod
spec:
  restartPolicy: OnFailure
  containers:
    - image: eicas.com/tpu-container:0.1.0
      name: pod-ctr
      command: ["sleep"]
      args: ["100000"]

      resources:
        limits:
          eicas.com/tpu: 1