apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: tpu-device-plugin-daemonset
  namespace: kube-system
spec:
  selector:
    matchLabels:
      name: tpu-device-plugin-ds
  updateStrategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        name: tpu-device-plugin-ds
    spec:
      hostNetwork: true
      tolerations:
        - key: eicas.com/tpu
          operator: Exists
          effect: NoSchedule
      priorityClassName: "system-node-critical"
      containers:
        - image: eicas/tpu-device-plugin:v0.1.0
          name: tpu-device-plugin-ctr
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop: ["ALL"]
          volumeMounts:
            - name: device-plugin
              mountPath: /var/lib/kubelet/device-plugins
      volumes:
        - name: device-plugin
          hostPath:
            path: /var/lib/kubelet/device-plugins